install:
  # conda
  - curl -fSsLO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe
  - set CONDA_ROOT="%UserProfile%\Miniforge3"
  - Miniforge3-Windows-x86_64.exe /InstallationType=JustMe /S /D=%CONDA_ROOT%
  - call %CONDA_ROOT%\Scripts\activate.bat
  - conda install -y -c conda-forge openturns joblib ipyparallel pathos numpy nose

build_script:
  - nosetests --nocapture
